apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace 'com.example.karanlikmod'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.karanlikmod"
        // OPPO AX7 (CPH1903) Android 8.1.0 = API 27
        minSdk 27
        targetSdk 27
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
